export const COORDINATES_MAX_X = 20
export const COORDINATES_MAX_Y = 20

export const RESOURCE_NODES_AMOUNT = 20

// income parameters
export const RESOURCE_HARVESTER_CAPACITY = 1000
export const RESOURCE_HARVESTER_MINING_SPEED = 2000
export const RESOURCE_HARVESTER_UNLOAD_SPEED = 5000
export const RESOURCE_HARVESTER_TRAVEL_SPEED = 10
